name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Append Last.fm API key to PHP file
        run: |
          # Use sed to replace the API key placeholder in the /src/nowplaying.php file
          sed -i "s/\$api_key = '';/\$api_key = '${{ secrets.LASTFM_API_KEY }}';/" /src/nowplaying.php

          # Check if any changes were made
          git diff --exit-code || exit 0

      - name: Commit changes to GitHub if there are changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add /src/nowplaying.php
          git commit -m "Appended Last.fm API key from secrets" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Deploy to Hostinger via Webhook
        run: |
          curl -X POST 'https://example.com/hooks/deploy?key=abc123'  # Replace with your Hostinger webhook URL
