name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Append Last.fm API key to PHP file
        run: |
          sed -i "s/\$api_key = '';/\$api_key = '${{ secrets.LASTFM_API_KEY }}';/" nowplaying.php

      - name: Commit changes to GitHub
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add nowplaying.php
          git commit -m "Appended Last.fm API key from secrets"
          git push
